import type { Metadata } from "next";
import { Inter, Lexend } from "next/font/google";
import "./globals.css";
import Footer from "@/components/footer/Footer";
import NavbarClient from "@/components/nabvar/Navclient";
import FlatIcon from "@/components/flatIcon/flatIcon";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "MEWE",
  description: "Generated by create next app",
};

const lexend = Lexend({
  subsets: ["latin"],
  weight: ["300", "400", "600", "700", "900"],
  variable: "--font-lexend",
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={lexend.variable}>
      <body className="font-lexend">
        <NavbarClient />
        {children}
        <Link href={{ pathname: "/account", query: { tab: "chat" } }}>
          <div className="fixed bottom-0 right-3 px-1 sm:px-2 md:px-4 lg:px-6 py-1 sm:py-2 md:py-3 bg-[#054A91] cursor-pointer  text-white rounded-t-xl w-[15%] flex justify-center gap-1 sm:gap-2 md:gap-3 z-40">
            <h1 className="md:text-base sm:text-sm text-xs">CHAT</h1>
            <FlatIcon className="flaticon-down-right-2 text-white text-xs sm:text-sm md:text-base font-bold drop-shadow-2xl" />
          </div>
        </Link>
        <Footer />
      </body>
    </html>
  );
}
