import type { Metadata } from "next";
import { Inter, Lexend } from "next/font/google";
import "./globals.css";
import Footer from "@/components/footer/Footer";
import NavbarClient from "@/components/nabvar/Navclient";
import ChatButton from "@/components/chatButton/ChatButton";
import Providers from "../utils/provider";
import { ToastContainer } from "react-toastify";
import ChatContextProvider from  "../utils/ChatContext"

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "MEWE",
  description: "Generated by create next app",
};

const lexend = Lexend({
  subsets: ["latin"],
  weight: ["300", "400", "600", "700", "900"],
  variable: "--font-lexend",
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={lexend.variable}>
      <body className="font-lexend">
        <ChatContextProvider>
        <Providers>
          <NavbarClient />
          {children}
          <ChatButton />
          <Footer />
        </Providers>
        </ChatContextProvider>
        <ToastContainer />
      </body>
    </html>
  );
}
